alpha: 0.0005
alpha_decay: 0
batch_size: 20
beam_size: 20
bleu_validation_weight: 1
cell_type: lstm
classif_filter:
  alpha: 0.001
  batch_size: 20
  delex_slots: name,area,address,phone,good_for_meal,near,food,price_range,count,price,postcode
  emb_size: 50
  language: cs
  max_tree_len: 50
  min_passes: 10
  nn: emb
  nn_shape: bidi_rnn
  num_hidden_units: 128
  passes: 100
  randomize: true
  selector: ''
  validation_freq: 1
context_bleu_weight: 0
dropout_keep_prob: 0.5
emb_size: 200
improve_interval: 50
language: cs
lexicalizer:
  alpha: 0.001
  alpha_decay: 0.0
  batch_size: 20
  bidi: true
  cell_type: lstm
  emb_size: 50
  form_sample: false
  form_select_type: rnnlm
  max_cores: 4
  max_grad_norm: 10
  max_sent_len: 32
  min_passes: 0
  optimizer_type: adam
  passes: 50
  randomize: true
max_cores: 8
min_passes: 50
mode: tokens
nn_type: emb_bidi_attention_seq2seq
num_hidden_units: 128
optimizer_type: adam
passes: 1000
randomize: true
selector: ''
ref_selectors: ''
sort_da_emb: true
top_k: 10
use_context: false
use_dec_cost: false
use_div_token: false
validation_delex_slots: name,area,address,phone,good_for_meal,near,food,price_range,count,price,postcode
validation_freq: 1
validation_no_overlap: true
validation_size: 300
validation_use_all_refs: true
validation_use_train_refs: false
